const FLOWERS = [
  { name: "Abutilon", meaning: "Meditation", scientificName: "" },
  { name: "Acacia", meaning: "Secret love", scientificName: "" },
  { name: "Acanthus", meaning: "Artifice", scientificName: "" },
  { name: "Agapanthus", meaning: "Love letter", scientificName: "" },
  { name: "Allium", meaning: "Prosperity", scientificName: "" },
  { name: "Almond blossom", meaning: "Indiscretion", scientificName: "" },
  { name: "Aloe", meaning: "Grief", scientificName: "" },
  { name: "Alstroemeria", meaning: "Devotion", scientificName: "" },
  { name: "Alyssum", meaning: "Worth beyond beauty", scientificName: "" },
  { name: "Amaranth", meaning: "Immortality", scientificName: "" },
  { name: "Amaryllis", meaning: "Pride", scientificName: "" },
  { name: "Anemone", meaning: "Forsaken", scientificName: "" },
  { name: "Angelica", meaning: "Inspiration", scientificName: "" },
  { name: "Apple", meaning: "Temptation", scientificName: "" },
  { name: "Apple blossom", meaning: "Preference", scientificName: "" },
  { name: "Aster", meaning: "Patience", scientificName: "" },
  { name: "Azalea", meaning: "Fragile and ephemeral passion", scientificName: "" },
  { name: "Baby's breath", meaning: "Everlasting love", scientificName: "" },
  { name: "Bachelor's button", meaning: "Single blessedness", scientificName: "" },
  { name: "Basil", meaning: "Hate", scientificName: "" },
  { name: "Bay leaf", meaning: "I change but in death", scientificName: "" },
  { name: "Begonia", meaning: "Caution", scientificName: "" },
  { name: "Bellflower", meaning: "Gratitude", scientificName: "" },
  { name: "Bells of Ireland", meaning: "Good luck", scientificName: "" },
  { name: "Bird of paradise", meaning: "Magnificence", scientificName: "" },
  { name: "Blackberry", meaning: "Envy", scientificName: "" },
  { name: "Black-eyed Susan", meaning: "Justice", scientificName: "" },
  { name: "Bluebell", meaning: "Constancy", scientificName: "" },
  { name: "Bougainvillea", meaning: "Passion", scientificName: "" },
  { name: "Bouvardia", meaning: "Enthusiasm", scientificName: "" },
  { name: "Broom", meaning: "Humility", scientificName: "" },
  { name: "Buttercup", meaning: "Ingratitude", scientificName: "" },
  { name: "Cabbage", meaning: "Profit", scientificName: "" },
  { name: "Calla lily", meaning: "Modesty", scientificName: "" },
  { name: "Camellia", meaning: "My destiny is in your hands", scientificName: "" },
  { name: "Candytuft", meaning: "Indifference", scientificName: "" },
  { name: "Canterbury bells", meaning: "Constancy", scientificName: "" },
  { name: "Carnation", meaning: "Mother's eternal love, heartache", scientificName: "Dianthus caryophyllus" },
  { name: "Carnation, pink", meaning: "I will never forget you", scientificName: "Dianthus caryophyllus" },
  { name: "Carnation, red", meaning: "My heart breaks", scientificName: "Dianthus caryophyllus" },
  { name: "Carnation, striped", meaning: "I cannot be with you", scientificName: "Dianthus caryophyllus" },
  { name: "Carnation, white", meaning: "Sweet and lovely", scientificName: "Dianthus caryophyllus" },
  { name: "Carnation, yellow", meaning: "Disdain", scientificName: "Dianthus caryophyllus" },
  { name: "Celandine", meaning: "Joys to come", scientificName: "" },
  { name: "Chamomile", meaning: "Energy in adversity", scientificName: "" },
  { name: "Cherry blossom", meaning: "Impermanence", scientificName: "" },
  { name: "Chervil", meaning: "Sincerity", scientificName: "" },
  { name: "Chestnut", meaning: "Do me justice", scientificName: "" },
  { name: "Chicory", meaning: "Frugality", scientificName: "" },
  { name: "Chrysanthemum", meaning: "Truth", scientificName: "" },
  { name: "Cinquefoil", meaning: "Beloved daughter", scientificName: "" },
  { name: "Clematis", meaning: "Poverty", scientificName: "" },
  { name: "Clove", meaning: "I have loved you and you have not known it", scientificName: "" },
  { name: "Clover, white", meaning: "Think of me", scientificName: "" },
  { name: "Cockscomb", meaning: "Affection", scientificName: "" },
  { name: "Columbine", meaning: "Desertion", scientificName: "" },
  { name: "Coreopsis", meaning: "Always cheerful", scientificName: "" },
  { name: "Coriander", meaning: "Hidden worth", scientificName: "" },
  { name: "Corn", meaning: "Riches", scientificName: "" },
  { name: "Cosmos", meaning: "Joy in love and life", scientificName: "" },
  { name: "Cowslip", meaning: "Pensiveness", scientificName: "" },
  { name: "Crab-apple blossom", meaning: "Ill-tempered", scientificName: "" },
  { name: "Cranberry", meaning: "Cure for heartache", scientificName: "" },
  { name: "Crocus", meaning: "Youthful gladness", scientificName: "" },
  { name: "Currant", meaning: "Thy frown will kill me", scientificName: "" },
  { name: "Cyclamen", meaning: "Timid hope", scientificName: "" },
  { name: "Cypress", meaning: "Mourning", scientificName: "" }
];

if (typeof window !== "undefined") {
  window.FLOWERS = FLOWERS;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = FLOWERS;
}
